"""add email confirmation

Revision ID: 7de82337731a
Revises: f8ea9532e6b7
Create Date: 2026-05-14 12:59:26.307463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7de82337731a'
down_revision: Union[str, Sequence[str], None] = 'f8ea9532e6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING', 'ACTIVE', 'DEACTIVATED', 'BANNED', name='emailstatus').create(op.get_bind())
    op.create_table('email_confirmation_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hashed_token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_confirmation_tokens_hashed_token'), 'email_confirmation_tokens', ['hashed_token'], unique=True)
    op.create_index(op.f('ix_email_confirmation_tokens_user_id'), 'email_confirmation_tokens', ['user_id'], unique=False)
    op.add_column('users', sa.Column('email_status', postgresql.ENUM('PENDING', 'ACTIVE', 'DEACTIVATED', 'BANNED', name='emailstatus', create_type=False), nullable=False, server_default="PENDING"))
    op.alter_column("users", "email_status", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_status')
    op.drop_index(op.f('ix_email_confirmation_tokens_user_id'), table_name='email_confirmation_tokens')
    op.drop_index(op.f('ix_email_confirmation_tokens_hashed_token'), table_name='email_confirmation_tokens')
    op.drop_table('email_confirmation_tokens')
    sa.Enum('PENDING', 'ACTIVE', 'DEACTIVATED', 'BANNED', name='emailstatus').drop(op.get_bind())
    # ### end Alembic commands ###
