"""add zip_url

Revision ID: c7aee57cfa38
Revises: 7de82337731a
Create Date: 2026-05-15 09:34:14.623937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7aee57cfa38'
down_revision: Union[str, Sequence[str], None] = '7de82337731a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zipped_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(length=255), nullable=False),
    sa.Column('zip_token', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zipped_urls_user_id'), 'zipped_urls', ['user_id'], unique=False)
    op.create_index(op.f('ix_zipped_urls_zip_token'), 'zipped_urls', ['zip_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zipped_urls_zip_token'), table_name='zipped_urls')
    op.drop_index(op.f('ix_zipped_urls_user_id'), table_name='zipped_urls')
    op.drop_table('zipped_urls')
    # ### end Alembic commands ###
